version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: securepay-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SecurePay@2026!
      - POSTGRES_DB=securepay
    ports:
      - "5432:5432"
    restart: unless-stopped